### PR TITLE
freexl v2.0.0

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
*  Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Alternative to #29.
- Introduces `libkml` as build requirement.
- Refreshes patches.

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
Nothing like attempting to use a new package as a dependency to realize it has a bug conda-forge/minizip-feedstock#4

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
didn't wait long enough for the CDN to update, but rewrote the commits to hopefully have this in a clean state for merging.  Will try again in an hour or two :)

**Comment by akrherz** [comment]
@conda-forge-admin please restart ci

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

@ocefpaf , this should be green and ready for your review.

**Review by ocefpaf — APPROVED** [review]
@akrherz amazing work here and with minizip! Thanks!!

Do you want to add yourself as a maintainer before I merge this one?

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Pull request merged**
