### PR TITLE
MNT: rerender

### LINKED ISSUE #14: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #14.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #14

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Something weird is happening with Windows. The DLL is installed, but it can't be found or it links to something that cannot be found. Here's the [CI build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=177866&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77 ). Also have [attached the logs]( https://github.com/conda-forge/freexl-feedstock/files/4823367/logs_177866.zip ).


```
(%PREFIX%) %SRC_DIR%>"%PREFIX%\python.exe" -s "%SRC_DIR%\run_test.py" 
===== testing package: freexl-1.0.5-h251d4ce_1003 =====
running run_test.py
Traceback (most recent call last):
  File "D:\bld\freexl_1592976060169\test_tmp\run_test.py", line 12, in <module>
    libfreexl = ctypes.CDLL('freexl.dll')
  File "D:\bld\freexl_1592976060169\_test_env\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'freexl.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by mariusvniekerk** [comment]
Closed by #21

**Pull request closed without merging**
