### PR TITLE
Trigger a rebuild to build against minizip 4.0.7 due to renaming of libminizip.dll to minizip.dll between 4.0.6 and 4.0.7

### PR DESCRIPTION
**Pull request by rouault**
…

See https://github.com/conda-forge/gdal-feedstock/issues/1027#issuecomment-2537599781

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rouault** [comment]
@conda-forge-admin, please rerender

**Comment by rouault** [comment]
@conda-forge-admin, please rerender

**Comment by rouault** [comment]
seems ok:
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1106851&view=logs&jobId=fe7faf59-69bb-5487-b8fd-a35a7bda3a51&j=fe7faf59-69bb-5487-b8fd-a35a7bda3a51&t=55731638-dd49-5144-2129-5101b9dd1960:
   INFO (freexl,Library/bin/freexl.dll): Needed DSO Library/bin/minizip.dll found in conda-forge/win-64::minizip==4.0.7=h9fa1bad_1
```

**Comment by rouault** [comment]
hum this pull request might have been undesirable seeing https://github.com/conda-forge/admin-requests/pull/1219 . I'm really confused...

**Comment by rouault** [comment]
ok, seeing now that there has been a change in minizip to restore libminizip.dll: https://github.com/conda-forge/minizip-feedstock/commit/0fb9e985fb5efa053667dcf9728a85531b069801

**Comment by akrherz** [comment]
Yeah, the main branch build did fail.  I am worried that my file rename hack left some cmake files pointing at the wrong lib filename yet.

```
LINK : fatal error LNK1104: cannot open file '%PREFIX%\Library\lib\minizip.lib'
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.EXE"' : return code '0x450'
Stop.
```

**Pull request merged**
